version: "3.9"
services:
  mysql-instance:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - /mysql-flaskapp/storage:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # instance should not be exposed
    ports:
      - 3306:3306
  ory-kratos-migrate: # Instance to control migrations
    depends_on: 
      - mysql-instance
    image: oryd/kratos:latest
    environment: 
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(mysql-instance)/MoviePollsDb?max_conns=20&max_idle_conns=4
    volumes: 
      - ./kratos-files:/etc/config/kratos
    command: 
      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  ory-kratos:
    depends_on: 
      - ory-kratos-migrate
    image: oryd/kratos:latest
    ports: 
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment: 
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(mysql-instance)/MoviePollsDb?max_conns=20&max_idle_conns=4
    volumes: 
      - ./kratos-files:/etc/config/kratos
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    
